export const SCREEN_NAMES = {
  DrawerNavigation: 'DrawerNavigation',
  App: 'App',

  Onboarding: 'Onboarding',
  LoginScreen: 'LoginScreen',
  Password: 'Password',
  Register: 'Register',
  ResetPassword: 'ResetPassword',
  DashBoard: 'DashBoard',
  ChangePassword: 'ChangePassword',
  MyBooking: 'MyBooking',
  Coupons: 'Coupons',
  Payment: 'Payment',
  Editprofile: 'Editprofile',
  Setting: 'Setting',
  Vehicles: 'Vehicles',
  AddVehicle: 'AddVehicle',
  AddCard: 'AddCard',
  Page: 'Page',
  VerifyOtp: 'VerifyOtp',
  TrackingFlow: 'TrackingFlow',

  PickupDetail: 'PickupDetail',
  Services: 'Services',
  ServiceRequestDetail: 'ServiceRequestDetail',

  // BankList: 'BankList',
  // BankDetail: 'BankDetail',
  // Transactions: 'Transactions',
  // AddMoney: 'AddMoney',
  // User: 'User',
  // PaymentDetail: 'PaymentDetail',
  // WalletList: 'WalletList',
  // SendMoney: 'SendMoney',
  // Profile: 'Profile',
  // HelpSupport: 'HelpSupport',
  // PrivacyPolicy: 'PrivacyPolicy',
  // SendMessage: 'SendMessage',
  // PinScreen: 'PinScreen',
  // SendMoneyNew: 'SendMoneyNew',
};
